### PR TITLE
Fix #501

### LINKED ISSUE #501: False default initializer when initializing with ""
```d
string a;
writeln(a is null); // true
string b = ""; // initializer is useless
writeln(b is null); // false
string c = null; // nothing
writeln(c is null); // true
```
As seen here `a` is null by default ant not `""`, so the initializer warning is showing wrong information

### PR DESCRIPTION
**Pull request by WebFreak001**
because `"" !is string.init` and is sometimes what you want to return of a function instead of `null`

### CODE REVIEW

**Comment by BBasile** [comment]
I disagree. `string a = "";` is clearly a useless initializer.

**Comment by WebFreak001** [comment]
```d
/// Returns: null if unsuccessful
string func()
{
  string ret = ""; // annoying wrong warning
  if (error)
    ret = null;
  return ret;
}
```

It does make sense, many string functions differentiate between `""` and `null` when returning. I don't want to get spammed with so many wrong dscanner warnings like this.

**Comment by BBasile** [comment]
The rule of thumb with D arrays is  "what counts is the `.length` property". All the cases that are handled by this check are compliant with this rule. The code you show is a really ugly abuse of D arrays to return a kind of error code.

**Comment by WebFreak001** [comment]
This is just example code, an actual implementation could receive from some TCP stream instead and instead of allocating a char[] for a result there return null which might even happen in two steps (making a local variable and then returning it)

**Comment by WebFreak001** [comment]
Or here I have an example from actual code:
```d
struct Part
{
  string contentType = null; /// Set to a string to clear or replace the content type, leave null to inherit
}
```

**Comment by BBasile** [comment]
Use the config file to disable the check.

**Comment by WebFreak001** [comment]
the problem is that dscanner tells me and other users wrong information, everyone will assume the initializer is not null if they use `""`

**Comment by BBasile** [comment]
Again i think you abuse of an implementation detail.
https://forum.dlang.org/post/mailman.2307.1382052843.1719.digitalmars-d@puremagic.com.
Even the language architect disagree with the usefulness of making the difference:
https://forum.dlang.org/post/l3rktv$uj9$1@digitalmars.com

**Comment by BBasile** [comment]
I don't like to split the community so you'll get merged. However i think that other people's mind would have been necessary to solve this controversy point of view.

**Comment by BBasile** [comment]
That being said i still think i was right. The point is that it's not that important, it's just a stupid and blind static check. The cases it covers shall be sufficient to make people understand that they don't need to initialize their variables..._"in case of..."_

**Pull request merged**
