### PR TITLE
Merge master into phobos

### PR DESCRIPTION
**Pull request by wilzbach**
Keeping the phobos branch up-to-date. `phobos` an experimental branch of Dscanner in which I can safely apply new features to be rolled out for Phobos.

### CODE REVIEW

**Comment by BBasile** [comment]
I see that you enabled the useless initializer but
- https://github.com/dlang-community/D-Scanner/pull/475 is not merged.
- the phobos PR that fixes the 538 case was rejected.
The only advice i can give you is to disable this check.

**Comment by wilzbach** [comment]
> I see that you enabled the useless initializer but

This is just a periodic sync from master to phobos

> #475 is not merged.

Will have a look into finally pushing it.

> The only advice i can give you is to disable this check.

It's disabled at Phobos: https://github.com/dlang/phobos/blob/e4afacadb8a291f51444e948dd7b53592e799dbe/.dscanner.ini#L156

**Comment by wilzbach** [comment]
> I don't understand, what do you use this branch for ?

Sorry that I didn't explain - merging & testing features like https://github.com/dlang-community/D-Scanner/pull/460 without needing to wait for review & approval. Inversely, Phobos has proven to be a good battlefield / playground to test new checks. So the intention is also to speed up reviewing by (1) improving a check, (2) showing that it works in real life.

A version of the `phobos` branch is checked out on Phobos when building Dscanner:
https://github.com/dlang/phobos/blob/master/posix.mak#L524

**Comment by BBasile** [comment]
Ok now i see that you filter std for the useless init check. Thanks for the explanations.

**Pull request merged**
