### PR TITLE
[WIP] Fix #493 - Add a check for documented symbols that aren't public

### LINKED ISSUE #493: Add a check for documented symbols that aren't public
From https://github.com/dlang/phobos/pull/5558

```
/// Add the mutable qualifier to the given type T.
package template MutableOf(T)     { alias MutableOf     =              T  ; }
```

Should yield a warning: "Documented symbol is not public".

### PR DESCRIPTION
**Pull request by wilzbach**
Issue: https://github.com/dlang-community/D-Scanner/issues/493

Todo:

- [ ] check for visibility applied with labels (`public:`)
- [ ] check for visibility applied with blocks (`public{...}`))

### CODE REVIEW

**Comment by BBasile** [comment]
I'm mitigated toward this check. I think that at least protected declarations must be excluded. Object oriented frameworks typically document the protected declarations so that the framework end-users know what to override.

However if this check is made with Phobos in mind then an option is to set it disabled by default.

**Comment by BBasile** [comment]
This one looks abandoned, closing.

**Comment by wilzbach** [comment]
This was part of the Phobos fork. I will rebase it over the next days.

**Comment by WebFreak001** [comment]
looks abandoned, closing.

Also I don't think this should be enabled by default, I ddoc my private symbols very often to have better documentation inside the editor (DCD showing ddoc)

**Pull request closed without merging**
