### PR TITLE
Switch to use the frozen stdx-allocator package

### PR DESCRIPTION
**Pull request by wilzbach**
Probably requires a quick bump once libdparse has been updated.

Requires: https://github.com/dlang-community/libdparse/pull/211 and https://github.com/dlang-community/containers/pull/95

### CODE REVIEW

**Comment by BBasile** [comment]
I'm tempted to say let's merge this one manually. The status of appveyor is not clear. Two of the tests don't even indicate any error at all.

**Comment by wilzbach** [comment]
I think in this case the error is legitimate - the `build.bat` file required updates - though I have no idea whether my changes are correct. I did them "blindly" on Linux.

**Comment by BBasile** [comment]
Of course. The bat.

**Comment by wilzbach** [comment]
> Two of the tests don't even indicate any error at all.

Yeah, not sure sure what we can do about this one:

```
Program exited with code -1073741819
```

**Comment by BBasile** [comment]
GTG on Windows to see what happened. Too bad the initiative to switch to stdx everywhere couldn't be finished this afternoon. Anyway, thanks for the quick reaction @wilzbach.

**Comment by BBasile** [comment]
It has to be okay now.

**Pull request merged**
