### PR TITLE
apply dfmt

### PR DESCRIPTION
**Pull request by stefan-koch-sociomantic**
I've just applied dfmt such that my editor stops complaining.
Maybe it's worth a pull ?

### CODE REVIEW

**Comment by stefan-koch-sociomantic** [comment]
ldc on travis fails b/c of network timeouts.

**Comment by wilzbach** [comment]
While I understand the motivation, this will cause me a lot of pain (rebasing all my PRs and branches) with almost no gain.
However, if there's consensus to go this way, I wouldn't object.
CC @Hackerpilot @BBasile @ZombineDev

**Comment by stefan-koch-sociomantic** [comment]
@wilzbach well apply dfmt to your prs.
it should result in the same diff

**Comment by wilzbach** [comment]
Fair enough, but git blame will be affected too.

**Comment by BBasile** [comment]
Two args for closing.

- DFMT is not mature enough
- unmaintained.

**Pull request closed without merging**
