### PR TITLE
Allow customizing the style check messages' format

### LINKED ISSUE #377: Allow custom formats of output errors
Hi,

I'd like to be able to format the errors printed when checking D files in the following manner:
```
{filename}:{line}:{column}: {kind}: {message}
```

Could this be possible, with a command line flag and/or a configuration file option?

Thanks.

### PR DESCRIPTION
**Pull request by lenormf**
Hi,

This patch allows external tools to parse the diagnostics more easily. The code that compiles the format is the most stupid&simple I could think of, but maybe there's a more idiomatic way to do it.

Closes #377

### CODE REVIEW

**Comment by BBasile** [comment]
more idiomatic is `std.algorithm.substitute` but it's much slower, even when casting to prevent auto -decoding. Your _stupid&simple_ version is actually hard to beat in performance:

```d
#!dmd -O -release -inline -boundscheck=off
module runnable;

import std.stdio, std.algorithm, std.typecons, std.range, std.array, std.conv;

string v1(string message)
{
    auto s = "{filepath}({line}:{column})[{type}]: {message}";
    const string fileName = "/home/folder/folter/source.d";
    const int line = 42;
    const int column = 13;

	s = s.replace("{filepath}", fileName);
	s = s.replace("{line}", to!string(line));
	s = s.replace("{column}", to!string(column));
	s = s.replace("{type}", "warn");
	s = s.replace("{message}", message);

    return s;
}

string v2(string message)
{
    string s = "{filepath}({line}:{column})[{type}]: {message}";
    string fileName = "/home/folder/folter/source.d";
    const int line = 42;
    const int column = 13;

    pragma(inline, true)
    auto rangeOf(string component)()
    {
        size_t p = (cast(ubyte[])s).countUntil(cast(ubyte[])component);
        return tuple(p, p + component.length);
    }

    s.replaceInPlace(rangeOf!"{filepath}"[0..$], fileName);
    s.replaceInPlace(rangeOf!"{line}"[0..$], to!string(line));
    s.replaceInPlace(rangeOf!"{column}"[0..$], to!string(column));
    s.replaceInPlace(rangeOf!"{type}"[0..$], "warn");
    s.replaceInPlace(rangeOf!"{message}"[0..$], message);

    return s;
}

string v3(string message)
{
    auto s = "{filepath}({line}:{column})[{type}]: {message}";
    const string fileName = "/home/folder/folter/source.d";
    const int line = 42;
    const int column = 13;
    const string isError = "warn";

    return cast(string) substitute(cast(ubyte[])s,
        cast(ubyte[])"{filepath}", cast(ubyte[])fileName,
        cast(ubyte[])"{column}", cast(ubyte[])to!string(column),
        cast(ubyte[])"{type}", cast(ubyte[])isError,
        cast(ubyte[])"{message}", cast(ubyte[])message
    ).array;
}

void main()
{
    import std.datetime.stopwatch;
    benchmark!((){v1("frst version");})(1_000_000).writeln;
    benchmark!((){v2("secd version");})(1_000_000).writeln;
    benchmark!((){v3("thrd version");})(1_000_000).writeln;
}
```

> [1 sec, 691 ms, 711 μs, and 9 hnsecs]
[1 sec, 488 ms, 807 μs, and 6 hnsecs]
[2 secs, 782 ms, 699 μs, and 6 hnsecs]

Considering that D-Scanner does not output hundreds of thousands of messages this is not worth changing your code.

LGTM as it.

**Comment by stefan-koch-sociomantic** [comment]
I can't say I love customizable message formats that much.

It's easy for two people do use slightly different formats.

**Comment by BBasile** [comment]
More idiomatic is `std.algorithm.iteration.substitute` but is also slower. Your _stupid&simple_ version is actually hard to beat:

```d
#!dmd -O -release -inline -boundscheck=off
module runnable;

import std.stdio, std.algorithm, std.typecons, std.range, std.array, std.conv, std.string;


string v1(string message)
{
    auto s = "{filepath}({line}:{column})[{type}]: {message}";
    const string fileName = "/home/folder/folter/source.d";
    const int line = 42;
    const int column = 13;

	s = s.replace("{filepath}", fileName);
	s = s.replace("{line}", to!string(line));
	s = s.replace("{column}", to!string(column));
	s = s.replace("{type}", "warn");
	s = s.replace("{message}", message);

    return s;
}

string v2(string message)
{
    string s = "{filepath}({line}:{column})[{type}]: {message}";
    string fileName = "/home/folder/folter/source.d";
    const int line = 42;
    const int column = 13;

    pragma(inline, true)
    auto rangeOf(string component)()
    {
        size_t p = (cast(ubyte[])s).countUntil(cast(ubyte[])component);
        return tuple(p, p + component.length);
    }

    s.replaceInPlace(rangeOf!"{filepath}"[0..$], fileName);
    s.replaceInPlace(rangeOf!"{line}"[0..$], to!string(line));
    s.replaceInPlace(rangeOf!"{column}"[0..$], to!string(column));
    s.replaceInPlace(rangeOf!"{type}"[0..$], "warn");
    s.replaceInPlace(rangeOf!"{message}"[0..$], message);

    return s;
}

string v3(string message)
{
    auto s = "{filepath}({line}:{column})[{type}]: {message}";
    const string fileName = "/home/folder/folter/source.d";
    const int line = 42;
    const int column = 13;
    const string isError = "warn";

    return cast(string) substitute(cast(ubyte[])s,
        cast(ubyte[])"{filepath}", cast(ubyte[])fileName,
        cast(ubyte[])"{line}", cast(ubyte[])to!string(column),
        cast(ubyte[])"{column}", cast(ubyte[])to!string(column),
        cast(ubyte[])"{type}", cast(ubyte[])isError,
        cast(ubyte[])"{message}", cast(ubyte[])message
    ).array;
}

void main()
{
    import std.datetime.stopwatch;
    benchmark!((){v1("frst version");})(1_000_000).writeln;
    benchmark!((){v2("secd version");})(1_000_000).writeln;
    benchmark!((){v3("thrd version");})(1_000_000).writeln;
}
```
>[1 sec, 653 ms, 920 μs, and 4 hnsecs]
[1 sec, 476 ms, 696 μs, and 7 hnsecs]
[3 secs, 41 ms, 312 μs, and 6 hnsecs]  (!!!)

So this is LGTM for me, en l'état.

**Comment by lenormf** [comment]
Thanks for the comments. I'd actually forgotten to modify some parts of the code that also printed errors, so I added a commit to fix that.

**Pull request merged**
