### PR TITLE
don't use deprecated properties

### PR DESCRIPTION
**Pull request by Moth-Tolias**
this silences some of the deprecation warnings emitted when building.

### CODE REVIEW

**Review by WebFreak001 — CHANGES_REQUESTED** [review]
you would need to bump the minimum libdparse version for this change. (see CI)

**Comment by Moth-Tolias** [comment]
should work now?

**Comment by Moth-Tolias** [comment]
oh dear, that doesn't look right...

**Comment by Moth-Tolias** [comment]
now tested to work with `dub upgrade`.

**Comment by WebFreak001** [comment]
you forgot to set the exact version to use when compiling D-Scanner as executable in dub.selections.json

the version range in dub.json is for library users to support multiple libdparse versions

**Comment by WebFreak001** [comment]
it seems that the new dsymbol versions doesn't work with old libdparse versions, you probably have to bump the minimum libdparse version some more.

**Comment by Moth-Tolias** [comment]
if it doesn't work this time i will become jokerfied

**Review by WebFreak001 — APPROVED** [review]

**Pull request merged**
