### PR TITLE
WIP: Support for exporting CodeClimate compatible reports.

### PR DESCRIPTION
**Pull request by nazriel**

### CODE REVIEW

**Comment by andre2007** [comment]
SonarQube has a report format "Generic Issue Data". This the reason for the SonarQube class name. I assume you copied the class name, but likely "generic issue data" does not make sense for your new class.

**Comment by rikkimax** [comment]
Based upon the old CI result, this might be mergeable.

But it'll need a push to trigger the current CI to verify that (I think).

**Comment by WebFreak001** [comment]
on master we now have diagnostic end locations / ranges, instead of just line and column, as well as supplemental diagnostic locations. You might want to integrate this in your report format.

**Comment by nazriel** [comment]
Hi guys, sorry for the troubles. I forgot about this MR.
I will close it and redo with newest code-base and your ideas

**Pull request closed without merging**
