### PR TITLE
actually bump libdparse now

### PR DESCRIPTION
**Pull request by WebFreak001**
forgot it last PR (#834)

### CODE REVIEW

**Comment by PetarKirov** [comment]
I think you also need to update the git submodule commit hash

**Comment by WebFreak001** [comment]
git submodule already points to the later version because of last PR (that's why this is the corrective PR)

**Comment by WebFreak001** [comment]
> ```
> Unresolvable dependencies to package libdparse:
>  dscanner 0.11.1+commit.3.g18867d4 depends on libdparse >=0.17.0 <0.19.0
>  dsymbol 0.11.3 depends on libdparse >=0.14.0 <0.18.0
>  libddoc 0.8.0 depends on libdparse >=0.13.0 <1.0.0
> ```

doesn't 0.17.x fit those restrictions? why would that be unresolvable?

**Comment by RazvanN7** [comment]
I think that this can be closed now.

**Pull request closed without merging**
