### PR TITLE
SonarQube external issue reporter added

### PR DESCRIPTION
**Pull request by andre2007**
This pull request adds the possibility to set message type and severity. Also an SonarQube external issue reporter is added.

### CODE REVIEW

**Comment by BBasile** [comment]
So for now the new `metadata()` methods are not used ? I think there's should be something that use them in a test or whatever. Actually i don't even see how they can be used.

**Comment by andre2007** [comment]
Yes you are right. I wanted to start with a rather small pr, but it makes sense to add a use case.

**Comment by BBasile** [comment]
I don't know. Maybe since each check as one or several KEY enum maybe in a first time each check could get as member a something like

```d
struct MessageDescriptor
{
    static string message; // this one is a bit problematic i think, it's mostly used to format...

    static string KEY;
    static MessageType type;
    static MessageSeverity severity;
}
```

Then when emitting a message you save 2 params

**Comment by andre2007** [comment]
@BBasile I think I did not really understood the static field in the struct and how it helps me.
I changed the pr and did a example implementation for alias_syntax_check. 
When the concept is OK and validated, I can change the other checks too.

**Comment by BBasile** [comment]
Indeed the fields must not be static. Sorry i have no idea why i suggested this.

**Comment by andre2007** [comment]
Any feedback ? :)

**Comment by andre2007** [comment]
@Basile-z is the used approach ok for you? If yes I would go on and adapt all analysis modules accordingly.

**Comment by andre2007** [comment]
As Jenkins is now able to read D-Scanner json report files, I close this pr.

**Pull request closed without merging**
